version: 2.1

orbs:
  release: sharptools/release@0.0.3

jobs:
  compile:
    docker:
      - image: cimg/go:1.12

    steps:
      - checkout

      - run:
          name: compile
          command: |
            mkdir releases
            curl -s -L https://github.com/Sharpz7/gopack/releases/download/0.1.2/install.sh | bash
            gopack --file install

            go build -o "sharpdev" ./src

          environment:
            GOOS: "linux"

      - run:
          name: tar
          command: |
            tar -czf ./releases/linux.tar.gz "sharpdev"
            cp -r ./installs/install.sh ./releases/install.sh

            mkdir ./workspace
            cp ./sharpdev ./workspace/sharpdev
            cp ./.version ./workspace/.version
            cp -r ./releases ./workspace/releases

      - persist_to_workspace:
          root: .
          paths:
            - ./workspace

workflows:
  workflow:
    jobs:
      - compile

      - release/github_job:
          context: General
          requires:
            - compile
          filters:
            branches:
              only: master
